Certify:

  template : /home/levi/Downloads/UI Certificate.pptx # location of the certificate template.pptx

  data: test.csv # location of the csv file.

  save_location : /home/levi/Documents/test # path where the location to be saved.

  variables:  # these are variables
    Full Name : Name
    email: Email

  # sent_email : True # It is a optional feild default is false.

  # content: text.txt  # path where the Body of the email is present [only .txt file.]
  # subject : Testin Mail
